### ISSUE TITLE
last version 3.2.1 not work

### ISSUE THREAD

**Issue by priore** [Marxon13/M13Checkbox#102]
I have multiple check boxes in a single view but they do not work, only one check is ticked when i tap on the any checkboxes, the previous version work right.

**Comment by Ahmedshubber** [comment]
@priore @erikprice @0x0c @szotyi @jefmwols I had the same problem. If you have more than one checkbox it only selects one checkbox and the others dont show. The old version worked perfectly and this one wont work. Can you fix it.

**Comment by originalduffus** [comment]
I have this issue too, Please fix.

Thanks!

**Comment by jackpaster** [comment]
+1 can you take a look at it. and fix it.

**Comment by prYmea** [comment]
Same problem with multiple checkboxes. Please fix.

**Comment by claudiocamara** [comment]
+1 Same problem

**Comment by mohammadshalhoob** [comment]
+1 Same problem

**Comment by sadaokiarata** [comment]
+1 Me too

**Comment by djmacross** [comment]
Temporal fix:
Replace this line 218 in M13Checkbox.swift 

    //fileprivate var controller: M13CheckboxController = DefaultValues.controller
with
     fileprivate var controller: M13CheckboxController = M13CheckboxStrokeController()

**Comment by nboyd-sportdx** [comment]
@djmacross THANK YOU

**Comment by HuangLiang-Jun** [comment]
@djmacross Thanks~! work now~

**Comment by butterpunk** [comment]
Any plans on permanently fixing this? I've imported this framework using carthage so I don't have access to M13Checkbox.swift. Checking on work arounds now.

**Comment by Marxon13** [comment]
Fixed merged. Updated pod version will be out shortly.
