### ISSUE TITLE
It does not working for multiple items

### ISSUE THREAD

**Issue by ZhuxianQuan** [Marxon13/M13Checkbox#103]
I have used M13Checkbox as select items before.

But it does not working.

It allows only an item

**Comment by djmacross** [comment]
Temporal fix:
Replace this line 218 in M13Checkbox.swift 

    //fileprivate var controller: M13CheckboxController = DefaultValues.controller
with
     fileprivate var controller: M13CheckboxController = M13CheckboxStrokeController()

**Comment by ZhuxianQuan** [comment]
Thank you.

I got it.

**Comment by Hendies567** [comment]
Had the same problem - I'd setup the M13Checkbox with a reusable tableview cell and had only one checkbox showing. djmacross' code fixed my issue.

It's definitely worth incorporating this into an update for this pod!

**Comment by daver234** [comment]
How do you get a M13CheckBox to show up in a re-usable tableview cell?  I added a 40x40 UIView and changed it to a M13CheckBox in IB.  But crashes when it trys to on: 
`checkBoxView.markType = .checkmark`

**Comment by daver234** [comment]
Got it working.  Needed to add the fix by djmacross and add as subview in tableview cell

**Comment by Nathan187** [comment]
@daver234 i have an app that is using this and now all of a sudden my checkboxes have disappeared.  they are in tableview cells...can you provide a code sample of your fix?   thanks

**Comment by daver234** [comment]
Just make the change listed on this page on Oct 19 by djmacross.  Did you try that and it didn't work?

**Comment by Nathan187** [comment]
i left a comment later saying thanks to djmacross. not sure why it got deleted.  (i used his suggestion and it worked)

**Comment by fjsosa** [comment]
same issue here, fixed with djmacross's fix

**Comment by Marxon13** [comment]
Fixed in master. Pod version update coming shortly.

**Comment by sungkim23** [comment]
Any updates on this? Was breaking my head for over 3 hours because no other cells would check until I found this fix by djmacross

**Comment by ipuntes** [comment]
Hi! I've incorporated this to my app and works fine until I scroll down. Then, because of these are reusable cells, the cells that appear after scrolling show checkmark sometimes. I've tried everything, even I do re draw the checkmarks when they are being showed (at the cellForRow method), but I've got no positive result...Could you help me on this? Thanks in advanced
