### ISSUE TITLE
Multiple section selection in tableView

### ISSUE THREAD

**Issue by ikyh** [Marxon13/M13Checkbox#111]
Hi,  Great Library...!! 

I have an Expanded TableView, which has a **checkBox-Label-radioButton** in `parentCell`(HeaderView) and a **checkBox-Label**  in childCell (ExpandedCell)

Now when I select a radioButton & checkBox of 0th index of `parentCell`, then the radioButton & checkBox of 10th and 20th index are also selected.
Also when I click on the checkBox of `childCell` then other the checkBoxes in other `childCells` are also selected. 

 I so don't want this to happen.

My requirement is that only a single radioButton should get selected when user clicks on `parentCell`. When user clicks on other `parentCell` then previously selected radioButton should get deselected and new one should get selected. That means only selection is allowed for radioButton. 

CheckBoxes in `parentCell` and `childCell` can have multiple selection. Also how to get the selection of radioButton/checkBox. I have to perform some operation when checkBox/radioButton is selected. 

Please help me solve this issue. Have just begun with swift. I am using Xcode 9, swift 3/4.

**Comment by andreaantonioni** [comment]
It seems like you are not using `prepareForReuse()` in your `UITableViewCell`, try to use it.
Actually this is not a library bug so I'm gonna close this issue
