### ISSUE TITLE
Storyboard couldn't render M13Checkbox

### ISSUE THREAD

**Issue by Dusknoir06** [Marxon13/M13Checkbox#116]
I added an UIView to my storyboard and set the class to M13Checkbox as well as the module but the storyboard can't render it.

I am using Xcode 9.3, Swift 4, and M13Checkbox 3.2.2

file:///Users/home/BowHead/Bowhead-iOS/Bowhead/Swift/Screens/Intro/IntroScreen.storyboard: error: IB Designables: Failed to render and update auto layout status for IntroPageTermsPolicyScreen (jQo-vK-aX3): dlopen(M13Checkbox.framework, 1): no suitable image found.  Did find:
	M13Checkbox.framework: required code signature missing for 'M13Checkbox.framework'

**Comment by justdan0227** [comment]
I'm getting that as well.  Any updates?

/CheckListTableViewCell.xib: error: IB Designables: Failed to render and update auto layout status for CheckListTableViewCell (KGk-i7-Jjw): dlopen(M13Checkbox.framework, 1): no suitable image found.  Did find:
	M13Checkbox.framework: required code signature missing for 'M13Checkbox.framework'

**Comment by tylerlantern** [comment]
Guys , I recommend to check this error at 
[](https://stackoverflow.com/questions/40110392/required-code-signature-missing-for-a-library)
the problem is seemed to be the pod itself.

**Comment by andreaantonioni** [comment]
It seems to not be a problem related to `M13Checkbox`, I tried to run the example app (which is in a storyboard) and it works even with Xcode 10 beta 1.

Try to follow the @tylerlantern tip 👍🏻
