### ISSUE TITLE
Error when setting class of view to M13Checkbox

### ISSUE THREAD

**Issue by bcye** [Marxon13/M13Checkbox#118]
Hey,

when setting the class of a 40x40 view to M13Checkbox it says:
```
[...]/Base.lproj/Main.storyboard: error: IB Designables: Failed to render and update auto layout status for TodayTableViewController (BaZ-Vd-Uvr): dlopen(M13Checkbox.framework, 1): no suitable image found.  Did find:
	M13Checkbox.framework: required code signature missing for 'M13Checkbox.framework'
```

Has someone an idea how this could be caused?
I tried setting the module to m13checkbox.

The app still builds and starts.

**Comment by imclean** [comment]
Try adding this to your pod file after your pods:
`post_install do |installer|
        installer.pods_project.build_configurations.each do |config|
            config.build_settings.delete('CODE_SIGNING_ALLOWED')
            config.build_settings.delete('CODE_SIGNING_REQUIRED')
        end
    end`

**Comment by bcye** [comment]
Perfect, thanks so much!
