### ISSUE TITLE
swift 4.2

### ISSUE THREAD

**Issue by BetilloGG** [Marxon13/M13Checkbox#132]
Hello, I'm trying to migrate my project to 4.2swift  with its library but I'm downloading version 3.2.2 which is 3.2 swift

**Comment by iMax21** [comment]
Same problem here, still downloading the 3.2.2 version even if I specified the tag

**Comment by andreaantonioni** [comment]
Sorry if it took to much to publish the version on cocoapods. Now it's available the `3.3.1` with swift 4.2 support
