### ISSUE TITLE
Checkbox display a line on top right when it is inside uitableviewcell for unchecked state

### ISSUE THREAD

**Issue by daarkfish** [Marxon13/M13Checkbox#29]
I have a configuredcell method for a custom uitableviewcell which initiate a m13checkbox everytime cellForRowAtIndexPath is called.

when I click on the checkbox in any row, the other checkboxes in random row will show a the box with a small line above the top right of the box whenever i scroll the UITableView. It will display like the image attached below

<img width="42" alt="tick" src="https://cloud.githubusercontent.com/assets/5997040/8646413/55337678-2982-11e5-9dad-7b1ab4c03442.png">

**Comment by Marxon13** [comment]
This issue should be fixed as of version 2.0.0.
