### ISSUE TITLE
Freeze when initializing with CGRectZero

### ISSUE THREAD

**Issue by mickeyl** [Marxon13/M13Checkbox#30]
I'm using M13Checkbox in a form where the layouting is separate from the creation, thus I initWIthFrame:CGRectZero, which leads to a freeze in core graphics:

![bildschirmfoto 2015-07-21 um 10 39 38](https://cloud.githubusercontent.com/assets/167469/8796411/e7a389f4-2f94-11e5-9769-360c3c0b35f8.png)

**Comment by Marxon13** [comment]
Interesting. This should no longer happen in as of version 2.0.0.
