### ISSUE TITLE
I want to fit the frame size with mlutiline text

### ISSUE THREAD

**Issue by ochim** [Marxon13/M13Checkbox#35]
I add the following method.
What do you think ?

//  M13Checkbox.m

- (void)autoSizeToFit {
    _titleLabel.numberOfLines = 0;
    _titleLabel.lineBreakMode = NSLineBreakByWordWrapping;

    CGSize margin = CGSizeMake(5.0, 5.0);
    CGRect labelrect = [_titleLabel.text
                        boundingRectWithSize:CGSizeMake(_titleLabel.bounds.size.width - margin.width * 2,
                                                        CGFLOAT_MAX)
                        options:NSStringDrawingUsesLineFragmentOrigin
                        attributes:@{
                                     NSFontAttributeName : _titleLabel.font
                                     }
                        context:nil];

    self.frame = CGRectMake(
                            self.frame.origin.x, self.frame.origin.y,
                            labelrect.size.width + ([self heightForCheckbox] * kCheckBoxSpacing) +
                            ((kBoxSize + kCheckHorizontalExtention) * [self heightForCheckbox]),
                            labelrect.size.height);

    [self layoutSubviews];
}

**Comment by Marxon13** [comment]
This is always a tricky problem, your code should work for a fixed width.
