### ISSUE TITLE
error in m13checkbox.swift

### ISSUE THREAD

**Issue by J-Arji** [Marxon13/M13Checkbox#39]
when i run app error 
Use of unresolved identifier 'M13CheckboxStrokeManager'
why ?

**Comment by Marxon13** [comment]
How are you building the app? Cocoa pods? Did you drag the source files into your project? It sounds like the `M13CheckboxStrokeManager` is not included in your target's compile sources.

**Comment by J-phantom** [comment]
Cocoa pods

**Comment by Marxon13** [comment]
Can you check and see if the file exists in the pods xcodeproj that is in the workspace.

**Comment by Marxon13** [comment]
Did you get it working?

**Comment by J-Arji** [comment]
No :(

**Comment by Marxon13** [comment]
Could you attach a screenshot of the pods project directory in xcworkspace, expanding the Pods group/folder in the cocoa pods sub-project, as well as the M13Checkbox folder under that.

**Comment by Marxon13** [comment]
If you are still looking to get this issue fixed, please let me know.

**Comment by J-Arji** [comment]
Thank you my problem was resolved  👍
