### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by dielsonsales** [Marxon13/M13Checkbox#40]
Build fails in this line:

```swift
let longPressGesture = M13CheckboxGestureRecognizer(target: self, action: #selector(M13Checkbox.handleLongPress(_:)))
```

with `Expected instruction in list of expressions` and `Expected ',' separator` and `Missing argument for parameter 'action' in call`.

**Comment by Marxon13** [comment]
Are you running the latest version of swift (2.2)?

**Comment by dielsonsales** [comment]
Not yet, still running Xcode 7.2
