### ISSUE TITLE
Changint tint color on checked state

### ISSUE THREAD

**Issue by antons81** [Marxon13/M13Checkbox#41]
Hi Pals, I am trying to implement your great checkbox, but when checking control it's changing my tint color to blue. How I can fix it. Is there some delegate methods to catch checked/unchecked values like 0 and 1?

**Comment by Marxon13** [comment]
What animation style are you using, is it all of them? 
There are three tint colors, the standard `tintColor`, the `secondaryTintColor` (unselected box color), and the `secondaryCheckmarkTintColor` (The check color when checked using a fill animation.)

The checkbox is a UIControl, so you can set a selector to run on UIControlEventValueChanged. Then check the checkbox's state.

**Comment by antons81** [comment]
I did it.I created a view and insert this class to my view. Through IB Designable I changed colors to the same color. And it changing it to blue tint color after animation and value changed

**Comment by andreaantonioni** [comment]
Going to close
