### ISSUE TITLE
Why the iOS 9 requirement in the pod spec?

### ISSUE THREAD

**Issue by mohpor** [Marxon13/M13Checkbox#44]

**Comment by Marxon13** [comment]
The version could probably be pushed back to iOS 8 or possibly 7. I can check this later and lower the version if possible.

**Comment by mohpor** [comment]
That'd be great

**Comment by vCrespoP** [comment]
100% agree. Please make it at least 8+

**Comment by Marxon13** [comment]
Project and spec now work with iOS 8.

**Comment by vCrespoP** [comment]
Working. 

Thanks man ;)
