### ISSUE TITLE
Use of unresolved indentifier "M13Checkbox"

### ISSUE THREAD

**Issue by joseDream** [Marxon13/M13Checkbox#45]
I'm using `pod` instalation.

It is not very clear to me, if there is to do something extra after this.

![captura de pantalla 2016-05-17 a las 9 47 30 p m](https://cloud.githubusercontent.com/assets/19420993/15346060/cc19b51e-1c79-11e6-8370-ee587370abca.png)

**Comment by Marxon13** [comment]
Make sure you import the header for M13Checkbox. You should use `#import <M13Checkbox/M13Checkbox.h>`

**Comment by Marxon13** [comment]
Did you get the issue resolved?

**Comment by vCrespoP** [comment]
Tested in Xcode 7.3.1:

* Update pod file (I'm using version 1.2.0 of M13Checkbox because I need iOS 8.x availability):
```
pod install / pod update
```

* I'm using frameworks in my podfile:
``` 
use_frameworks! 
```

* Import in your bridging-header the framework:
```
#ìmport<M13Checkbox/M13Checkbox.h>
```

* In your .swift file
```
ìmport M13Checkbox
```

**Comment by Marxon13** [comment]
I just updated M13Checkbox 2 to be comparable with iOS 8, try that.

**Comment by joseDream** [comment]
Works, thanks @vCrespoP
