### ISSUE TITLE
[iOS8] case stateChangeAnimation .Fill, setsetCheckState without animation not working.

### ISSUE THREAD

**Issue by yukitoto** [Marxon13/M13Checkbox#49]
if I use other animation style like bounds or stroke, this not happen.

**Comment by dmitrykurochka** [comment]
iOS 9 and iOS 10 the same issue

**Comment by Marxon13** [comment]
I can't seem to reproduce this issue. What version of M13Checkbox are you using? Could you try updating to the latest if not.

**Comment by andreaantonioni** [comment]
Going to close
