### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by hmalc** [Marxon13/M13Checkbox#50]
Hi guys. Love the framework and use it extensively in my apps.

Just wondering about support for Swift 3, since I'm hoping to release an app optimized for iOS10 on launch day.

If there's no plans underway it's something I'd be willing to help out with.

**Comment by Highstorm** [comment]
Would be awesome since the framework seems to have issues even with Swift 2.3

Greetings

**Comment by Marxon13** [comment]
See issue #57 for cocoa pods.
