### ISSUE TITLE
What about change events?

### ISSUE THREAD

**Issue by arcioneo** [Marxon13/M13Checkbox#51]
Hi, thanks for this amazing tool, today I faced 2 issues and my questions to those are:

- How can I capture the a check/uncheck event?

- Is there any way to set a hidden value like in HTML?

Many thanks in advance

**Comment by PatNeedham** [comment]
Hi @arcioneo,
I too wanted to know how capture the check/uncheck events and I found a solution. I made a UIView inside the storyboard and first changed the class to M13Checkbox. When control dragging the view to a Swift file, change the connection to action and by default the Event is of type "Value Changed". This IBAction gets called every time you check or uncheck the box. From there you can call whatever other methods you want!

**Comment by Marxon13** [comment]
@PatNeedham is correct. The checkbox is a subclass of UIControl, so you can attach IBActions for touch and value change events to it. As for the hidden property, UIControl is a subclass of UIView, which has a hidden property.
