### ISSUE TITLE
How to control the checkbox state manually?

### ISSUE THREAD

**Issue by fjim349** [Marxon13/M13Checkbox#54]
The checkbox state seems to be controlled by M13checkbox
how can I control it by my own code?
I tried setState but still no luck

**Comment by Marxon13** [comment]
The `checkState` variable, `setCheckState`, and `toggleCheckState` should do what you are looking for. The setState is provided by UIControl and is for touch events.

**Comment by SalahEddineKahack** [comment]
Hi, I'm trying to change set state to .checked manually but neither of these 3 ways works for me. the checkbox refuses to change state :(
