### ISSUE TITLE
Swift 2.3 - render issue within framework

### ISSUE THREAD

**Issue by Highstorm** [Marxon13/M13Checkbox#55]
Hey Folks,

since Xcode 8 is available and Swift 2.3 conversion is recommended i have an error within your Framework.

"error: IB Designables: Failed to render and update auto layout status for UIView (iN0-l3-epB): dlopen(M13Checkbox.framework, 1): Symbol not found: __TWPSis16ForwardIndexTypes
  Referenced from: M13Checkbox.framework
  Expected in: (shortended).../Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Xcode/Overlays/../../../../../../Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator/libswiftCore.dylib
 in M13Checkbox.framework

The whole xib is not renderable in interface builder if a m13checkbox is within a xib file. If i reset the class it runs until i reopen it in interface builder.

![screen shot 2016-09-10 at 10 45 08](https://cloud.githubusercontent.com/assets/5220699/18409286/b3833bcc-7743-11e6-8468-8ddf1393c04b.png)

I Want to use your framework further on so do you have any suggestion?

greetings

**Comment by Marxon13** [comment]
I've updated the project to Swift 3. That should fix all of the issues in Xcode 8.
