### ISSUE TITLE
Swift 3 Versions not available in Cocoapods.

### ISSUE THREAD

**Issue by Marxon13** [Marxon13/M13Checkbox#57]
Currently `pod trunk push` and `pod spec lint` are failing. Working on a fix, there is no clear solution that I can find. I tried overriding the `SWIFT_VERSION` config property, but that is not working. As soon as a solution is found, I'll update Cocoapods.

**Comment by mohpor** [comment]
Are you using Xcode 8 beta alongside other Xcodes?

I have faced the same problem with multiple Xcode. It seems like cocoapod can't figure build tools.

**Comment by mohpor** [comment]
For now: 

```ruby 
pod 'M13Checkbox' , :git => 'https://github.com/Marxon13/M13Checkbox.git'
```

**Comment by mohpor** [comment]
@Marxon13 I can see that the code is updated, pod spec has been updated and I still get the `2.1.2` from cocoapods. are you sure you have pushed the latest to the pod trunk?

**Comment by NickPappas** [comment]
Same. ^

**Comment by Marxon13** [comment]
Turns out, it needed a swift-version file in the repo, along with having swiftenv installed.
