### ISSUE TITLE
Are there way to use it on Swift 2.3?

### ISSUE THREAD

**Issue by shiratsu** [Marxon13/M13Checkbox#58]
I would like to use this library on swift 2.3 with xcode8.
But i could not find way to use.
This looks for only Swift3. 
Are there way to use it on Swift 2.3?
I am trying to fix swift branch then,I am trying to use it.

**Comment by Marxon13** [comment]
The library jumped over Swift 2.3 directly to Swift 3. I would recommend running the converted on the swift 2.2 version. There shouldn't be many changes.
