### ISSUE TITLE
Arrow drawing loses position in smaller frames.

### ISSUE THREAD

**Issue by rob-nash** [Marxon13/M13Checkbox#63]
Arrow position off centre at smaller sizes.

Larger (250 x 250)
![Larger](http://i.imgur.com/nDsr1no.png)

Smaller (30 x 30)
![Smaller](http://i.imgur.com/AVQUhv2.png)

**Comment by Marxon13** [comment]
What's interesting is that this is happening with the mixed mark too. The positions of that are based on 25% increments of the size.

**Comment by Marxon13** [comment]
Fixed in last commit. (Commit  3e4a4e4)
