### ISSUE TITLE
xcode 8(swift 3.0) not compatible

### ISSUE THREAD

**Issue by arcioneo** [Marxon13/M13Checkbox#65]
Cannot use this library in xcode 8(swift 3.0) 

<img width="1142" alt="screen shot 2016-09-28 at 13 50 13" src="https://cloud.githubusercontent.com/assets/5040537/18927678/82d34c36-8582-11e6-9456-e9fdb16e6070.png">

**Comment by Marxon13** [comment]
It looks like the incompatible library is Alamofire. This should be fixable by running the Swift 3 converter under Xcode's edit menu.

**Comment by Marxon13** [comment]
The latest version (2.2.4) is compatible with swift 3, so please be sure you are using that version as well.
