### ISSUE TITLE
Increased compilation times in Swift 3

### ISSUE THREAD

**Issue by szotyi** [Marxon13/M13Checkbox#66]
Hi, I'm seeing increased compilation times for this project (version 2.2.4) and it causes to XCode 8 to be really slow. I ran the command mentioned here: http://irace.me/swift-profiling and it gave me this:
```
17059.2ms       /XXX/Pods/M13Checkbox/Sources/M13CheckboxPathPresets.swift:113:43        get {}
16583.8ms       /XXX/Pods/M13Checkbox/Sources/M13CheckboxPathPresets.swift:113:43        get {}
10840.5ms       /XXX/Pods/M13Checkbox/Sources/M13CheckboxPathPresets.swift:76:55 get {}
10393.4ms       /XXX/Pods/M13Checkbox/Sources/M13CheckboxPathPresets.swift:76:55 get {}
```
The times vary, but they are always really high (min. 6000ms).
Can you look into it? Thanks

**Comment by szotyi** [comment]
There is an app https://github.com/RobertGummesson/BuildTimeAnalyzer-for-Xcode which you can use to profile your Demo project, the same way as on the mentioned webpage (just add the build paramaters to the M13Checkbox target also)

**Comment by Marxon13** [comment]
Pull request merged! Thanks, I'm going to be doing this analysis with all my projects now.
