### ISSUE TITLE
Checkmark line not complete

### ISSUE THREAD

**Issue by chomatdam** [Marxon13/M13Checkbox#69]
**M13Checkbox 2.2.5 via storyboard- XCode 8 - Swift 3 - iOS 10**

Hi,
     When I choose _Circle_ for IBBox Type with checked state, it's okay but when I choose _Square_, I only have half the line. Screenshots below

<div style="float:left">
<img width="75" alt="screen shot 2016-10-02 at 3 14 31 pm" src="https://cloud.githubusercontent.com/assets/8525860/19020799/ecf514b8-88b2-11e6-9727-4fb9bb8ce69e.png">
<img width="75" alt="screen shot 2016-10-02 at 3 14 18 pm" src="https://cloud.githubusercontent.com/assets/8525860/19020800/ef2f2cfa-88b2-11e6-8d7b-861dd9af0919.png">
</div>

**Comment by piegandolfi** [comment]
I have the same issue...
Some news?

**Comment by Marxon13** [comment]
The issue is caused by a NaN value produced on line 109 of M13CheckboxPathPresets. Why it wan't doing this before remains to be seen.
