### ISSUE TITLE
Expression was too complex - Swift 3

### ISSUE THREAD

**Issue by Relax594** [Marxon13/M13Checkbox#72]
Having issues using it in my Swift 3 project in **M13CheckboxPathPresets.swift**
I converted it to Swift 3 using Xcode Auto-Convert.

<img width="1018" alt="bildschirmfoto 2016-10-11 um 11 01 10" src="https://cloud.githubusercontent.com/assets/22765758/19264699/151cf172-8fa2-11e6-996f-24f0c04fc9be.png">

**Comment by Marxon13** [comment]
I'll have to break up that equation into two parts. Is that for x and y? Also which function is it in?

**Comment by Relax594** [comment]
Yes it is for x and y.
It is _**var checkmarkLongArmEndPoint: CGPoint**_

Can you also convert the code to Swift 3?

**Comment by Marxon13** [comment]
Version 2.2.1 and higher is swift 3.0.

**Comment by Relax594** [comment]
I just installed the pod and it installed 2.1.2 >.<
Updated it now..my fault.

**Comment by Marxon13** [comment]
Not a problem. The equations are still the same, and will probably still have issues anyway.

**Comment by Relax594** [comment]
Yep. I updated the pod now to 3.0 and Xcode still having problems with the equations.

**Comment by Marxon13** [comment]
Try version 3.1.1

**Comment by Relax594** [comment]
Build succeeded!

**Comment by Marxon13** [comment]
Cool. I'll close the issue then.
