### ISSUE TITLE
Cannot use in storyboard, with Carthage

### ISSUE THREAD

**Issue by maximelebastard** [Marxon13/M13Checkbox#74]
Hi,

as described in the README, I installed the library with Carthage and imported in in the Embed Frameworks, Embedded Binaries and Linked Frameworks and Libraries. I can instantiate a M13Checkbox object programmaticaly, add it as a subview and make it work.

But when I add a UIView to my storyboard, and I set (without autocomplete) the class to M13Checkbox (Identity Inspector > Custom class > Class - Module = "None"), I cannot see it as a M13Checkbox and edit its properties in the Attributes Inspector. Moreover, if I run the app I still have a UIView and not a M13Checkbox. 

Is there something I forgot to do ?

My app Deployment Target is 9.0 and I use Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38).

**Comment by Marxon13** [comment]
Try to set the module to M13Checkbox as well as the class. I've noticed that sometimes this does not happen automatically.

**Comment by tattva20** [comment]
I'm having the same problem, tried your suggestion but it didn't work

**Comment by Gujci** [comment]
Same here, I "solved" this by adding it as an outlet and set it up in the _didSet_ block. I know it's not the solution, but might help.

**Comment by nboyd-sportdx** [comment]
@Gujci can you explain a little more on what you did?  I spent an hour and a half now on this and about to give up and try a different library.  i too tried with carthage and tried the same things that was done previously by @maximelebastard 

i can create outlets but i can't attach them to actions (checkboxValueChanged)

**Comment by nboyd-sportdx** [comment]
copied the contents of the source code folder (and child folders) over.  this seems to work.  please update your documentation says that there are issues if you use carthage

**Comment by Gujci** [comment]
@nboyd-sportdx Shortly: I have added the checkbox in the storyboard but I did the setup from code.

**Comment by andreaantonioni** [comment]
I'm going to close this issue because it's quite old. Feel free to open a new issue if there's still a problem
