### ISSUE TITLE
`open class` instead of `public class`

### ISSUE THREAD

**Issue by TomVanDerSpek** [Marxon13/M13Checkbox#76]
Could you please make the M13Checkbox class `open` so it is possible to subclass it?

**Comment by Marxon13** [comment]
What are you trying to do that requires sub-classing?

**Comment by shining228** [comment]
Example, subclass it and implement a radio group that allows only one checkbox selected,  and the selected one will not change state when it has been touched

**Comment by darecki** [comment]
I just created a related PR. https://github.com/Marxon13/M13Checkbox/pull/78
I also used a subclass in Swift 2, and after migrating my code to Swift 3 it stopped working.

**Comment by Marxon13** [comment]
Merged.
