### ISSUE TITLE
How to set a label at the checkbox?

### ISSUE THREAD

**Issue by giofid** [Marxon13/M13Checkbox#77]
Hi,
sorry for the silly question, but how can I add a label at the checkbox?

**Comment by Marxon13** [comment]
I would use auto layout constraints either programmatically or in a storyboard. Use these to position the checkbox relative to a `UILabel`. Take a look at this [tutorial](https://www.raywenderlich.com/50317/beginning-auto-layout-tutorial-in-ios-7-part-1) on how to use auto layout.

**Comment by alexsorokoletov** [comment]
@Marxon13 how do I add a label so that touching the label would trigger the checkbox? Same as labels in HTML?
