### ISSUE TITLE
Crash on iOS 8.2

### ISSUE THREAD

**Issue by JanusHuang** [Marxon13/M13Checkbox#82]
When I use version 3.1.3, the app crashed, the detail is as followed:
![image](https://cloud.githubusercontent.com/assets/3005525/22055578/c34d8c1a-dd96-11e6-80c3-52a1c739540b.png)
![image](https://cloud.githubusercontent.com/assets/3005525/22055585/cd2ae2a0-dd96-11e6-8e8a-0c7c23ff8094.png)

**Comment by andreaantonioni** [comment]
Going to close
