### ISSUE TITLE
M_PI deprecated warnings

### ISSUE THREAD

**Issue by MihaiPantiru** [Marxon13/M13Checkbox#85]
On Xcode 8.3 (beta) the library is generating 33 warnings about M_PI being deprecated on Swift 3. The recommendation is to use CGFloat.pi instead.

**Comment by mwaqasbhati** [comment]
can any body make a pull request to remove these warnings on xcode 8.3.2 or it's already updated .... thanks

**Comment by NSMyself** [comment]
I think the repository itself is already updated, but the pod isn't.

**Comment by hammadzz** [comment]
@Marxon13 can we do a release? I can help.

**Comment by andreaantonioni** [comment]
I'll publish a minor version as soon I'll receive the cocoapods permission 👍
