### ISSUE TITLE
get checkState as Bool?

### ISSUE THREAD

**Issue by stealdre** [Marxon13/M13Checkbox#87]
How can I get the checkState as Bool and not as "checked" and "unchecked"??

**Comment by chenbobby** [comment]
if you want, you can create a helper function
`func checkState(checkbox: M13Checkbox) -> Bool { 
return checkbox._IBCheckState == "Checked" }`
and then run it whenever you need the checkState as Bool
`checkState(checkbox: MyCheckbox)`
