### ISSUE TITLE
Set associated Text with checkbox

### ISSUE THREAD

**Issue by maasim94** [Marxon13/M13Checkbox#89]
I'm adding checkbox in swift 3 project, I'm not able to find any title property which i can set with button to inform user what this check box is for?
I've searched there is not UILable in control, some objective-C  related question seems to be called with title, but there is no initializer that i've found

**Comment by drjasonharrison** [comment]
+1 we've had to add our own text, and make it a UIButton in order to have a larger hit area.

**Comment by andreaantonioni** [comment]
Actually `M13Checkbox` provides just the checkmark and not a `UILabel` to describe it.
