### ISSUE TITLE
Extraneous Argument Label 'type' in call with Xcode 8.3 (8E162)

### ISSUE THREAD

**Issue by jungalwala** [Marxon13/M13Checkbox#92]
I am getting compiler errors using M13Checkbox 3.1.3 and XCode 8.3.

/M13Checkbox/Sources/M13CheckboxController.swift:56:24: Extraneous argument label 'type:' in call
/M13Checkbox/Sources/M13Checkbox.swift:383:35: Extraneous argument label 'type:' in call
/M13Checkbox/Sources/M13Checkbox.swift:471:31: Extraneous argument label 'type:' in call

**Comment by andreaantonioni** [comment]
Going to close
